SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [bh176331].[AGENT](
    [Agent_ID] DECIMAL(5, 0) NOT NULL,
    [Name] [varchar](40) NOT NULL,
    [Phone_number] [varchar](15) NOT NULL,
    [Email] [varchar](320) NOT NULL,
    [Employment_agency] [varchar](100) NOT NULL,
    FOREIGN KEY (Agent_ID) REFERENCES PROPERTY(Property_ID)
    ON DELETE CASCADE
)

ALTER TABLE [AGENT] ADD  CONSTRAINT [PK_AGENT] PRIMARY KEY CLUSTERED 
(
	[Agent_ID] ASC,
    [Name] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO 

SET ANSI_PADDING ON
GO
ALTER TABLE [AGENT]  WITH CHECK ADD  CONSTRAINT [CK_AGENT_NAME_FORMAT] CHECK (Name NOT LIKE '%[^A-Za-z ]%')
GO
ALTER TABLE [AGENT] CHECK CONSTRAINT [CK_AGENT_NAME_FORMAT]
GO

SET ANSI_PADDING ON
GO
ALTER TABLE [AGENT] WITH CHECK ADD CONSTRAINT [CK_AGENT_PHONE_NUMBER_FORMAT] CHECK (Phone_number NOT LIKE '%[^0-9+ -]%')
GO
ALTER TABLE [AGENT] CHECK CONSTRAINT [CK_AGENT_PHONE_NUMBER_FORMAT]
GO

SET ANSI_PADDING ON
GO
ALTER TABLE AGENT 
ADD CONSTRAINT CK_AGENT_EMAIL_FORMAT CHECK (
       Email NOT LIKE '% %' AND 
       Email NOT LIKE '%.%@%' AND 
       Email NOT LIKE '%..%' AND 
       Email NOT LIKE '%@%-%.' AND 
       Email NOT LIKE '%.' AND 
       Email NOT LIKE '@%' AND 
       Email NOT LIKE '%@' 
);
GO

ALTER TABLE [AGENT] CHECK CONSTRAINT [CK_AGENT_EMAIL_FORMAT]
GO



SET ANSI_PADDING ON
GO
ALTER TABLE [AGENT]  WITH CHECK ADD  CONSTRAINT [CK_AGENT_EMPLOYMENT_AGENCY_FORMAT] CHECK (Employment_agency LIKE '%[^A-Za-z ]%')
GO
ALTER TABLE [AGENT] CHECK CONSTRAINT [CK_AGENT_EMPLOYMENT_AGENCY_FORMAT]
GO
