SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [bh176331].[EXISTS_IN_NEIGHBORHOOD](
    [City] [varchar](50) NOT NULL,
    [Name] [varchar](100) NOT NULL,
    [Property_ID] DECIMAL(5, 0) NOT NULL,
    FOREIGN KEY ([City], [Name])
    REFERENCES [NEIGHBORHOOD] ([City], [Name])
    ON DELETE CASCADE,
    FOREIGN KEY (Property_ID) REFERENCES PROPERTY(Property_ID)
    ON DELETE CASCADE
)

ALTER TABLE [EXISTS_IN_NEIGHBORHOOD] ADD  CONSTRAINT [PK_EXISTS_IN_NEIGHBORHOOD] PRIMARY KEY CLUSTERED 
(
	[City] ASC,
    [Name] ASC,
    [Property_ID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO 


