SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [bh176331].[EXISTS_IN_SCHOOL_DISTRICT](
    [District_ID] DECIMAL(5, 0) NOT NULL,
    [Property_ID] DECIMAL(5, 0) NOT NULL,
    FOREIGN KEY (District_ID) REFERENCES SCHOOL_DISTRICT(District_ID)
    ON DELETE CASCADE,
    FOREIGN KEY (Property_ID) REFERENCES PROPERTY(Property_ID)
    ON DELETE CASCADE
)

ALTER TABLE [EXISTS_IN_SCHOOL_DISTRICT] ADD  CONSTRAINT [PK_EXISTS_IN_SCHOOL_DISTRICT] PRIMARY KEY CLUSTERED 
(
	[District_ID] ASC,
    [Property_ID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO

