SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [bh176331].[HOA](
    [City] [varchar](50) NOT NULL,
    [Name] [varchar](100) NOT NULL,
    [HOA_name] [varchar](100) NOT NULL,
    [Phone_number] [varchar](15) NOT NULL,
    [Email] [varchar](320) NOT NULL,
    FOREIGN KEY ([City], [Name])
    REFERENCES [NEIGHBORHOOD] ([City], [Name])
    ON DELETE CASCADE
)

ALTER TABLE [HOA] ADD  CONSTRAINT [PK_HOA] PRIMARY KEY CLUSTERED 
(
	[City] ASC,
    [Name] ASC,
    [HOA_name] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO

SET ANSI_PADDING ON
GO
ALTER TABLE [HOA]  WITH CHECK ADD  CONSTRAINT [CK_HOA_NAME_FORMAT] CHECK (HOA_name NOT LIKE '%[^A-Za-z ]%')
GO
ALTER TABLE [HOA] CHECK CONSTRAINT [CK_HOA_NAME_FORMAT]
GO

SET ANSI_PADDING ON
GO
ALTER TABLE [HOA] WITH CHECK ADD CONSTRAINT [CK_HOA_PHONE_NUMBER_FORMAT] CHECK (Phone_number NOT LIKE '%[^0-9+ -]%')
GO
ALTER TABLE [HOA] CHECK CONSTRAINT [CK_HOA_PHONE_NUMBER_FORMAT]
GO

SET ANSI_PADDING ON
GO
ALTER TABLE [HOA] WITH CHECK ADD CONSTRAINT [CK_HOA_EMAIL_FORMAT] CHECK (
    Email NOT LIKE '% %' AND 
       Email NOT LIKE '%.%@%' AND 
       Email NOT LIKE '%..%' AND 
       Email NOT LIKE '%@%-%.' AND 
       Email NOT LIKE '%.' AND 
       Email NOT LIKE '@%' AND 
       Email NOT LIKE '%@' 
)
GO
ALTER TABLE [HOA] CHECK CONSTRAINT [CK_HOA_EMAIL_FORMAT]
GO

