SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [bh176331].[HOA_RULE](
    [City] [varchar](50) NOT NULL,
    [Name] [varchar](100) NOT NULL,
    [HOA_name] [varchar](100) NOT NULL,
    [Name_of_rule] [varchar](100) NOT NULL,
    [Rule_description] [varchar](500) NULL,
    FOREIGN KEY ([City], [Name], [HOA_name])
    REFERENCES [HOA] ([City], [Name], [HOA_name])
    ON DELETE CASCADE
)

ALTER TABLE [HOA_RULE] ADD  CONSTRAINT [PK_HOA_RULE] PRIMARY KEY CLUSTERED 
(
	[City] ASC,
    [Name] ASC,
    [HOA_name] ASC,
    [Name_of_rule] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO

SET ANSI_PADDING ON
GO
ALTER TABLE [HOA_RULE]  WITH CHECK ADD  CONSTRAINT [CK_HOA_RULE_NAME_OF_RULE_FORMAT] CHECK (Name_of_rule NOT LIKE '%[^A-Za-z ]%')
GO
ALTER TABLE [HOA_RULE] CHECK CONSTRAINT [CK_HOA_RULE_NAME_OF_RULE_FORMAT]
GO

SET ANSI_PADDING ON
GO
ALTER TABLE [HOA_RULE]  WITH CHECK ADD  CONSTRAINT [CK_HOA_RULE_DESCRIPTION_FORMAT] CHECK (Rule_description LIKE '%[^A-Za-z ]%')
GO
ALTER TABLE [HOA_RULE] CHECK CONSTRAINT [CK_HOA_RULE_DESCRIPTION_FORMAT]
GO

