SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [bh176331].[HOA_FEE](
    [City] [varchar](50) NOT NULL,
    [Name] [varchar](100) NOT NULL,
    [HOA_name] [varchar](100) NOT NULL,
    [Name_of_service] [varchar](100) NOT NULL,
    [When_collected] [varchar](30) NOT NULL,
    [Amount] DECIMAL(10, 2) NOT NULL,
    FOREIGN KEY ([City], [Name], [HOA_name])
    REFERENCES [HOA] ([City], [Name], [HOA_name])
    ON DELETE CASCADE
)

ALTER TABLE [HOA_FEE] ADD  CONSTRAINT [PK_HOA_FEE] PRIMARY KEY CLUSTERED 
(
	[City] ASC,
    [Name] ASC,
    [HOA_name] ASC,
    [Name_of_service] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO

SET ANSI_PADDING ON
GO
ALTER TABLE [HOA_FEE]  WITH CHECK ADD  CONSTRAINT [CK_HOA_FEE_NAME_OF_SERVICE_FORMAT] CHECK (Name_of_service NOT LIKE '%[^A-Za-z ]%')
GO
ALTER TABLE [HOA_FEE] CHECK CONSTRAINT [CK_HOA_FEE_NAME_OF_SERVICE_FORMAT]
GO

SET ANSI_PADDING ON
GO
ALTER TABLE [HOA_FEE]  WITH CHECK ADD  CONSTRAINT [CK_HOA_FEE_WHEN_COLLECTED_FORMAT] CHECK (When_collected NOT LIKE '%[^A-Za-z ]%')
GO
ALTER TABLE [HOA_FEE] CHECK CONSTRAINT [CK_HOA_FEE_WHEN_COLLECTED_FORMAT]
GO

ALTER TABLE [HOA_FEE]  WITH CHECK ADD  CONSTRAINT [CK_HOA_FEE_AMOUNT_NN] CHECK (Amount >= 0)
GO
ALTER TABLE [HOA_FEE] CHECK CONSTRAINT [CK_HOA_FEE_AMOUNT_NN]
GO 