SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [bh176331].[HOUSE](
    [House_ID] DECIMAL(5, 0) NOT NULL,
    [Basement] DECIMAL(1, 0) NOT NULL,
    [Garage] DECIMAL(2, 0) NOT NULL,
    [Bedrooms] DECIMAL(2, 0) NOT NULL,
    [Bathrooms] DECIMAL(3, 1) NOT NULL,
    [Stories] DECIMAL(2, 0) NOT NULL,
    [Year_built] INT,
    [Square_footage] DECIMAL(8, 2) NOT NULL,
    FOREIGN KEY (House_ID) REFERENCES PROPERTY(Property_ID)
    ON DELETE CASCADE
)

ALTER TABLE [HOUSE] ADD  CONSTRAINT [PK_HOUSE_House_ID] PRIMARY KEY CLUSTERED 
(
	[House_ID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO

ALTER TABLE [HOUSE] WITH CHECK ADD CONSTRAINT [CK_BASEMENT] CHECK (Basement IN (0, 1))
GO
ALTER TABLE [HOUSE] CHECK CONSTRAINT [CK_BASEMENT]
GO

ALTER TABLE [HOUSE] WITH CHECK ADD CONSTRAINT [CK_GARAGE] CHECK (Garage >= 0 AND Garage <= 10)
GO
ALTER TABLE [HOUSE] CHECK CONSTRAINT [CK_GARAGE]
GO

ALTER TABLE [HOUSE] WITH CHECK ADD CONSTRAINT [CK_STORIES] CHECK (Stories >= 0 AND Stories <= 10)
GO
ALTER TABLE [HOUSE] CHECK CONSTRAINT [CK_STORIES]
GO

ALTER TABLE [HOUSE] WITH CHECK ADD CONSTRAINT [CK_YEAR_BUILT] CHECK (Year_built BETWEEN 1000 AND 9999)
GO
ALTER TABLE [HOUSE] CHECK CONSTRAINT [CK_YEAR_BUILT]
GO

ALTER TABLE [HOUSE] WITH CHECK ADD CONSTRAINT [CK_SQUARE_FOOTAGE] CHECK (Square_footage >= 0)
GO
ALTER TABLE [HOUSE] CHECK CONSTRAINT [CK_SQUARE_FOOTAGE]
GO






