SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [bh176331].[INSPECTS](
    [Company_ID] DECIMAL(5, 0) NOT NULL,
    [House_ID] DECIMAL(5, 0) NOT NULL,
    [Report_file_path] [varchar](4096) NOT NULL,
    FOREIGN KEY (Company_ID) REFERENCES INSPECTION_COMPANY(Company_ID) ON DELETE CASCADE,
    FOREIGN KEY (House_ID) REFERENCES HOUSE(House_ID) ON DELETE CASCADE
)

ALTER TABLE [INSPECTS] ADD  CONSTRAINT [PK_INSPECTS] PRIMARY KEY CLUSTERED 
(
	[Company_ID] ASC,
    [House_ID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO

ALTER TABLE [INSPECTS] WITH CHECK ADD CONSTRAINT [CK_REPORT_FILE_PATH] CHECK (Report_file_path NOT LIKE '%[<>:"\\|?*]%' AND Report_file_path LIKE '/%')
GO
ALTER TABLE [INSPECTS] CHECK CONSTRAINT [CK_REPORT_FILE_PATH]
GO