SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [bh176331].[INSPECTION_COMPANY](
        [Company_ID] [char](5) NOT NULL,
        [Name] [varchar](100) NOT NULL,
        [Phone_number] [varchar](15) NOT NULL,
        [Email] [varchar](320) NOT NULL,
)
SET ANSI_PADDING ON
GO 
ALTER TABLE [INSPECTION_COMPANY] ADD  CONSTRAINT [PK_COMPANY_ID] PRIMARY KEY CLUSTERED 
(
	[Company_ID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO 
ALTER TABLE [INSPECTION_COMPANY]  WITH CHECK ADD  CONSTRAINT [CK_COMPANY_ID_FORMAT] CHECK (Company_ID LIKE '[0-9][0-9][0-9][0-9][0-9]')
GO
ALTER TABLE [INSPECTION_COMPANY] CHECK CONSTRAINT [CK_COMPANY_ID_FORMAT]
GO
SET ANSI_PADDING ON
GO 
ALTER TABLE [INSPECTION_COMPANY]  WITH CHECK ADD  CONSTRAINT [CK_COMPANY_NAME_FORMAT] CHECK (Name NOT LIKE '%[^A-Za-z ]%')
GO
ALTER TABLE [INSPECTION_COMPANY] CHECK CONSTRAINT [CK_COMPANY_NAME_FORMAT]
GO
SET ANSI_PADDING ON
GO
ALTER TABLE [INSPECTION_COMPANY] ADD  CONSTRAINT [UN_COMPANY_NAME] UNIQUE NONCLUSTERED 
(
	[Name] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
ALTER TABLE [INSPECTION_COMPANY] WITH CHECK ADD CONSTRAINT [CK_COMPANY_PHONE_NUMBER_FORMAT] CHECK (Phone_number NOT LIKE '%[^0-9+ -]%')
GO
ALTER TABLE [INSPECTION_COMPANY] CHECK CONSTRAINT [CK_COMPANY_PHONE_NUMBER_FORMAT]
GO
SET ANSI_PADDING ON
GO
ALTER TABLE [INSPECTION_COMPANY] WITH CHECK ADD CONSTRAINT [CK_COMPANY_EMAIL_FORMAT] CHECK (Email LIKE '%@%.%' AND 
       Email NOT LIKE '% %' AND 
       Email NOT LIKE '%.%@%' AND 
       Email NOT LIKE '%..%' AND 
       Email NOT LIKE '%@%-%.' AND 
       Email NOT LIKE '%.%' AND 
       Email NOT LIKE '@%' AND 
       Email NOT LIKE '%@%' AND
       Email NOT LIKE '%[^A-Za-z0-9@._+-]%')

GO
ALTER TABLE [INSPECTION_COMPANY] CHECK CONSTRAINT [CK_COMPANY_Email_FORMAT]
GO

