SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [bh176331].[NEIGHBORHOOD](
    [City] [varchar](50) NOT NULL,
    [Name] [varchar](100) NOT NULL
)

ALTER TABLE [NEIGHBORHOOD] ADD  CONSTRAINT [PK_NEIGHBORHOOD] PRIMARY KEY CLUSTERED 
(
	[City] ASC,
    [Name] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO

SET ANSI_PADDING ON
GO
ALTER TABLE [NEIGHBORHOOD]  WITH CHECK ADD  CONSTRAINT [CK_NEIGHBORHOOD_CITY_FORMAT] CHECK (City NOT LIKE '%[^A-Za-z ]%')
GO
ALTER TABLE [NEIGHBORHOOD] CHECK CONSTRAINT [CK_NEIGHBORHOOD_CITY_FORMAT]
GO

SET ANSI_PADDING ON
GO
ALTER TABLE [NEIGHBORHOOD]  WITH CHECK ADD  CONSTRAINT [CK_NEIGHBORHOOD_NAME_FORMAT] CHECK (Name NOT LIKE '%[^A-Za-z ]%')
GO
ALTER TABLE [NEIGHBORHOOD] CHECK CONSTRAINT [CK_NEIGHBORHOOD_NAME_FORMAT]
GO