SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [bh176331].[OPEN_HOUSE](
    [House_ID] DECIMAL(5, 0) NOT NULL,
    [Date] DATE NOT NULL,
    [Time] TIME NOT NULL,
    FOREIGN KEY (House_ID) REFERENCES PROPERTY(Property_ID)
    ON DELETE CASCADE
)

ALTER TABLE [OPEN_HOUSE] ADD  CONSTRAINT [PK_OPEN_HOUSE_House_ID] PRIMARY KEY CLUSTERED 
(
	[House_ID] ASC,
    [Date] ASC,
    [Time] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO



