SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [bh176331].[PIECE_OF_LAND](
    [Land_ID] DECIMAL(5, 0) NOT NULL,
    [Acreage] DECIMAL(10, 2) NOT NULL,
    [Terrain] [varchar](50) NOT NULL,
    FOREIGN KEY (Land_ID) REFERENCES PROPERTY(Property_ID)
    ON DELETE CASCADE
)

ALTER TABLE [PIECE_OF_LAND] ADD  CONSTRAINT [PK_PIECE_OF_LAND_LAND_ID] PRIMARY KEY CLUSTERED 
(
	[Land_ID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO

ALTER TABLE [PIECE_OF_LAND] WITH CHECK ADD CONSTRAINT [CK_ACREAGE_NN] CHECK (Acreage >= 0)
GO
ALTER TABLE [PIECE_OF_LAND] CHECK CONSTRAINT [CK_ACREAGE_NN]
GO

SET ANSI_PADDING ON
GO
ALTER TABLE [PIECE_OF_LAND]  WITH CHECK ADD  CONSTRAINT [CK_TERRAIN_FORMAT] CHECK (Terrain NOT LIKE '%[^A-Za-z ]%')
GO
ALTER TABLE [PIECE_OF_LAND] CHECK CONSTRAINT [CK_TERRAIN_FORMAT]
GO
