SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [bh176331].[PREFERENCE](
    [Preference_ID] DECIMAL(5, 0) NOT NULL,
    [Type] [varchar](10) NOT NULL,
    [Yes_or_no] [varchar](5) NULL,
    [Value] DECIMAL(3, 1) NULL,
    [Min] DECIMAL(3, 1) NULL,
    [Max] DECIMAL(3, 1) NULL,
)

ALTER TABLE [PREFERENCE] ADD  CONSTRAINT [PK_PREFERENCE_Preference_ID] PRIMARY KEY CLUSTERED 
(
	[Preference_ID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO

ALTER TABLE [PREFERENCE]  WITH CHECK ADD  CONSTRAINT [CK_PREFERENCE_ID_NN] CHECK (Preference_ID >= 0)
GO
ALTER TABLE [PREFERENCE] CHECK CONSTRAINT [CK_PREFERENCE_ID_NN]
GO

ALTER TABLE [PREFERENCE] WITH CHECK ADD CONSTRAINT [CK_TYPE] CHECK (Type IN ('YesNo', 'MinMax', 'Value'))
GO
ALTER TABLE [PREFERENCE] CHECK CONSTRAINT [CK_TYPE]
GO

ALTER TABLE [PREFERENCE] WITH CHECK ADD CONSTRAINT [CK_YES_OR_NO] CHECK (Yes_or_no IN ('Yes', 'No') OR Yes_or_no IS NULL)
GO
ALTER TABLE [PREFERENCE] CHECK CONSTRAINT [CK_YES_OR_NO]
GO

ALTER TABLE [PREFERENCE]  WITH CHECK ADD  CONSTRAINT [CK_VALUE_NN] CHECK ( Value >= 0)
GO
ALTER TABLE [PREFERENCE] CHECK CONSTRAINT [CK_VALUE_NN]
GO

ALTER TABLE [PREFERENCE]  WITH CHECK ADD  CONSTRAINT [CK_MIN_NN] CHECK (Min >= 0)
GO
ALTER TABLE [PREFERENCE] CHECK CONSTRAINT [CK_MIN_NN]
GO

ALTER TABLE [PREFERENCE]  WITH CHECK ADD  CONSTRAINT [CK_MAX_NN] CHECK (Max >= 0)
GO
ALTER TABLE [PREFERENCE] CHECK CONSTRAINT [CK_MAX_NN]
GO

