SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [bh176331].[SCHOOL_DISTRICT](
    [District_ID] DECIMAL(5, 0) NOT NULL,
    [Name] [varchar](100) NOT NULL,
    [Type] [varchar](30) NOT NULL
)

ALTER TABLE [SCHOOL_DISTRICT] ADD  CONSTRAINT [PK_SCHOOL_DISTRICT_District_ID] PRIMARY KEY CLUSTERED 
(
	[District_ID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO

ALTER TABLE [SCHOOL_DISTRICT] WITH CHECK ADD CONSTRAINT [CK_DISTRICT_ID_NN] CHECK (District_ID >= 0)
GO
ALTER TABLE [SCHOOL_DISTRICT] CHECK CONSTRAINT [CK_DISTRICT_ID_NN]
GO 

SET ANSI_PADDING ON
GO
ALTER TABLE [SCHOOL_DISTRICT]  WITH CHECK ADD  CONSTRAINT [CK_DISTRICT_NAME_FORMAT] CHECK (Name NOT LIKE '%[^A-Za-z ]%')
GO
ALTER TABLE [SCHOOL_DISTRICT] CHECK CONSTRAINT [CK_DISTRICT_NAME_FORMAT]
GO

SET ANSI_PADDING ON
GO
ALTER TABLE [SCHOOL_DISTRICT]  WITH CHECK ADD  CONSTRAINT [CK_SCHOOL_DISTRICT_TYPE_FORMAT] CHECK (Type IN ('Elementary', 'Middle', 'High'))
GO
ALTER TABLE [SCHOOL_DISTRICT] CHECK CONSTRAINT [CK_SCHOOL_DISTRICT_TYPE_FORMAT]
GO
